import aiohttp
import asyncio
from loguru import logger
from aiohttp import TCPConnector
import requests

url = "https://172.16.12.207/auth/realms/ataldev/protocol/openid-connect/token"

payload = "audience=data-service&grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Auma-ticket&response_mode=decision&permission=site_a%2F*%23data%3Arealtime%3Aread"
headers = {
    "Authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJEOXEzdmxoVGhNODBHNE1tNC1mZ1IxX0liYU9IYTRuQlJCWHZBR2xURE5zIn0.eyJleHAiOjE2NzU0MDY4MzUsImlhdCI6MTY3NTQwNjUzNSwiYXV0aF90aW1lIjoxNjc1NDAyNDExLCJqdGkiOiIzZGVjNzRhZC1jNzBlLTQ4NDQtODI0MC01OGM0ZTQ1MzQ4NGMiLCJpc3MiOiJodHRwczovLzE3Mi4xNi4xMi4yMDcvYXV0aC9yZWFsbXMvYXRhbGRldiIsImF1ZCI6WyJncmFmYW5hIiwiYWNjb3VudCJdLCJzdWIiOiJkMmQ1OGY5NS02NDU5LTRjZWUtOWI0Ny1hNjgwYzdkNzFiMWMiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiIzcmQtcGFydHkiLCJzZXNzaW9uX3N0YXRlIjoiNDdhZWFiYzktNzJmOC00MjMxLWFhZGYtODIzZmQ4NWYxOTk5IiwiYWNyIjoiMCIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwiZGVmYXVsdC1yb2xlcy1hdGFsZGV2Il19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiZ3JhZmFuYSI6eyJyb2xlcyI6WyJhZG1pbiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwic2lkIjoiNDdhZWFiYzktNzJmOC00MjMxLWFhZGYtODIzZmQ4NWYxOTk5IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInByZWZlcnJlZF91c2VybmFtZSI6ImF0YWwiLCJnaXZlbl9uYW1lIjoiIiwiZmFtaWx5X25hbWUiOiIiLCJlbWFpbCI6ImF0YWxAdGIuY29tIn0.Gw2_B34klktvMxzHDnU3_Gxv6m1h9ENBsWJeyxgGTLxC7FOsUsJ-TsNQt5BIOvXVkHADJ_PNC-mJN_wRAmHqxY3ACRHGGy7MVf_J9Pac554hqdg6ztTKh-PJeKB6UflJYLGadD1jHndwORVzQegMewv4SqrYWV08Isj9_ln7da9vcns2AbL7hdDrV024pxi_hlT-7jvOpljKqnTtBwnGTvnQp9t_cl_Zr20wEwgCiJ2O2v4aGXkfz-iLaXVf9vXYaVMZTPsakdUQ-ZP_0zxN4e6YUZzgJZBI8EUKYeAMiZL63mEtNpvcw3zVhfbhRgHMwXsMbrphXPNxGTAfeV9enw",
    "Content-Type": "application/x-www-form-urlencoded",
}

response = requests.request("POST", url, headers=headers, data=payload, verify=False)

print(response.text)
